# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "72d5ae318b1e3976f8a37c2890dc114d"
name = "virtual-shopkeeper"
handle = "virtual-shopkeeper"
application_url = "https://rpm-travel-designed-kai.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders,read_draft_orders"

[auth]
redirect_urls = [
  "https://rpm-travel-designed-kai.trycloudflare.com/auth/callback",
  "https://rpm-travel-designed-kai.trycloudflare.com/auth/shopify/callback",
  "https://rpm-travel-designed-kai.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
